routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::domain(config('cms.FRONT_DOMAIN'))->middleware('lang_check', 'web')->name('front.')->group(function () {
    Route::get('/{url?}', 'Xsoft\Cms\Controllers\Front\PageController@index')->where('url', '[A-Za-z0-9_/-]+')->name('index');
});

Route::domain(config('cms.ADMIN_DOMAIN'))->middleware('web')->name('admin.')->group(function () {
    Route::get('login', 'Xsoft\Cms\Controllers\Admin\Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Xsoft\Cms\Controllers\Admin\Auth\LoginController@login');
    Route::post('logout', 'Xsoft\Cms\Controllers\Admin\Auth\LoginController@logout')->name('logout');
    Route::middleware(['auth'])->group(function () {
        Route::get('/', 'Xsoft\Cms\Controllers\Admin\DashboardController@index')->name('dashboard')->middleware('permission:cms.login');
        Route::get('/instruction', 'Xsoft\Cms\Controllers\Admin\DashboardController@instruction')->name('instruction')->middleware('permission:cms.login');
        Route::prefix('pages')->name('pages.')->group(function () {
            Route::get('/', 'Xsoft\Cms\Controllers\Admin\PageController@index')->name('index')->middleware('permission:pages.show');
            Route::post('create', 'Xsoft\Cms\Controllers\Admin\PageController@store')->name('store')->middleware('permission:pages.create');
            Route::post('preview', 'Xsoft\Cms\Controllers\Admin\PageController@preview')->name('preview')->middleware('permission:pages.show');
            Route::get('frontPreview/{pageLanguage}', 'Xsoft\Cms\Controllers\Admin\PageController@frontPreview')->name('frontPreview')->middleware('permission:pages.show');
            Route::post('getPageDetails', 'Xsoft\Cms\Controllers\Admin\PageController@getPageDetails')->name('getPageDetails')->middleware('permission:pages.show');
            Route::post('updateDetails', 'Xsoft\Cms\Controllers\Admin\PageController@updateDetails')->name('updateDetails')->middleware('permission:pages.edit');
            Route::post('activatePage', 'Xsoft\Cms\Controllers\Admin\PageController@activatePage')->name('activatePage')->middleware('permission:pages.edit');
            Route::post('deactivatePage', 'Xsoft\Cms\Controllers\Admin\PageController@deactivatePage')->name('deactivatePage')->middleware('permission:pages.edit');
            Route::post('addLanguageVersion', 'Xsoft\Cms\Controllers\Admin\PageController@addLanguageVersion')->name('addLanguageVersion')->middleware('permission:pages.create');
            Route::post('getLanguagesSelect', 'Xsoft\Cms\Controllers\Admin\PageController@getLanguagesSelect')->name('getLanguagesSelect')->middleware('permission:pages.create');
            Route::post('addSection', 'Xsoft\Cms\Controllers\Admin\PageSectionController@addSection')->name('addSection')->middleware('permission:sections.create');
            Route::post('publish', 'Xsoft\Cms\Controllers\Admin\PageController@publish')->name('publish');
            Route::post('delete', 'Xsoft\Cms\Controllers\Admin\PageController@delete')->name('delete')->middleware('permission:pages.delete');
            Route::get('export/{page}', 'Xsoft\Cms\Controllers\Admin\PageController@export')->name('export')->middleware('permission:pages.export');
            Route::get('exportAll', 'Xsoft\Cms\Controllers\Admin\PageController@exportAllPages')->name('exportAll')->middleware('permission:pages.export');
            Route::post('import', 'Xsoft\Cms\Controllers\Admin\PageController@import')->name('import')->middleware('permission:pages.import');
            Route::post('getSections', 'Xsoft\Cms\Controllers\Admin\PageController@getSections')->name('getSections')->middleware('permission:sections.create');
        });
        Route::prefix('pageSectionTemplates')->name('pageSectionTemplates.')->group(function () {
            Route::post('preview/{pageSectionTemplate}', 'Xsoft\Cms\Controllers\Admin\PageSectionTemplateController@preview')->name('preview')->middleware('permission:pages.show');
        });
        Route::prefix('sections')->name('sections.')->group(function () {
            Route::post('edit', 'Xsoft\Cms\Controllers\Admin\PageSectionController@edit')->name('edit')->middleware('permission:sections.edit');
            Route::post('update', 'Xsoft\Cms\Controllers\Admin\PageSectionController@update')->name('update')->middleware('permission:sections.edit');
            Route::post('delete', 'Xsoft\Cms\Controllers\Admin\PageSectionController@delete')->name('delete')->middleware('permission:sections.delete');
            Route::post('addWidget', 'Xsoft\Cms\Controllers\Admin\WidgetController@addWidget')->name('addWidget')->middleware('permission:widgets.create');
            Route::post('deleteWidget', 'Xsoft\Cms\Controllers\Admin\WidgetController@delete')->name('deleteWidget')->middleware('permission:widgets.delete');
            Route::post('sort', 'Xsoft\Cms\Controllers\Admin\PageSectionController@sort')->name('sort')->middleware('permission:sections.edit');
        });
        Route::prefix('containers')->name('containers.')->group(function () {
            Route::post('/add', 'Xsoft\Cms\Controllers\Admin\ContainerController@add')->name('add')->middleware('permission:sections.edit');
            Route::post('/edit', 'Xsoft\Cms\Controllers\Admin\ContainerController@edit')->name('edit')->middleware('permission:sections.edit');
            Route::post('/get', 'Xsoft\Cms\Controllers\Admin\ContainerController@get')->name('get')->middleware('permission:sections.edit');
            Route::post('/delete', 'Xsoft\Cms\Controllers\Admin\ContainerController@delete')->name('delete')->middleware('permission:sections.edit');
            Route::post('/move', 'Xsoft\Cms\Controllers\Admin\ContainerController@move')->name('move')->middleware('permission:sections.edit');
        });
        Route::prefix('widgetContents')->name('widgetContents.')->group(function () {
            Route::post('/getContent', 'Xsoft\Cms\Controllers\Admin\WidgetController@getContent')->name('getContent')->middleware('permission:widgets.edit');
            Route::post('/saveContent', 'Xsoft\Cms\Controllers\Admin\WidgetController@saveContent')->name('saveContent')->middleware('permission:widgets.edit');
            Route::post('/move', 'Xsoft\Cms\Controllers\Admin\WidgetController@move')->name('move')->middleware('permission:widgets.edit');
            Route::post('/copy', 'Xsoft\Cms\Controllers\Admin\WidgetController@copy')->name('copy')->middleware('permission:widgets.edit');
        });
        Route::prefix('pageConfig')->name('pageConfig.')->group(function () {
            Route::get('/', 'Xsoft\Cms\Controllers\Admin\PageConfigController@index')->name('index')->middleware('permission:page_config.show');
            Route::post('update', 'Xsoft\Cms\Controllers\Admin\PageConfigController@update')->name('update')->middleware('permission:page_config.edit');
            Route::post('getLink', 'Xsoft\Cms\Controllers\Admin\PageConfigController@getLink')->name('getLink')->middleware('permission:page_config.edit');
        });
        Route::prefix('site/languages')->name('frontLanguages.')->group(function () {
            Route::get('/', 'Xsoft\Cms\Controllers\Admin\FrontLanguageController@index')->name('index')->middleware('permission:front_languages.show');
            Route::get('ajax', 'Xsoft\Cms\Controllers\Admin\FrontLanguageController@indexAjax')->name('indexAjax')->middleware('permission:front_languages.show');
            Route::post('create', 'Xsoft\Cms\Controllers\Admin\FrontLanguageController@store')->name('store')->middleware('permission:front_languages.create');
            Route::get('{language}/edit', 'Xsoft\Cms\Controllers\Admin\FrontLanguageController@edit')->name('edit')->middleware('permission:front_languages.edit');
            Route::post('{language}/edit', 'Xsoft\Cms\Controllers\Admin\FrontLanguageController@update')->name('update')->middleware('permission:front_languages.edit');
            Route::post('{language}/change/state', 'Xsoft\Cms\Controllers\Admin\FrontLanguageController@stateChange')->name('change.state')->middleware('permission:front_languages.delete');
            Route::post('{language}/delete', 'Xsoft\Cms\Controllers\Admin\FrontLanguageController@delete')->name('delete')->middleware('permission:front_languages.delete');
            Route::get('{language}/export', 'Xsoft\Cms\Controllers\Admin\FrontLanguageController@export')->name('export')->middleware('permission:front_languages.exportImport');
            Route::post('import', 'Xsoft\Cms\Controllers\Admin\FrontLanguageController@import')->name('import')->middleware('permission:front_languages.exportImport');
        });
        Route::prefix('users')->name('users.')->group(function () {
            Route::get('/', 'Xsoft\Cms\Controllers\Admin\UserController@index')->name('index')->middleware('permission:users.show');
            Route::get('ajax', 'Xsoft\Cms\Controllers\Admin\UserController@indexAjax')->name('indexAjax')->middleware('permission:users.show');
            Route::post('create', 'Xsoft\Cms\Controllers\Admin\UserController@store')->name('store')->middleware('permission:users.create');
            Route::get('{user}/edit', 'Xsoft\Cms\Controllers\Admin\UserController@edit')->name('edit')->middleware('permission:users.edit');
            Route::post('{user}/edit', 'Xsoft\Cms\Controllers\Admin\UserController@update')->name('update')->middleware('permission:users.edit');
            Route::delete('{user}', 'Xsoft\Cms\Controllers\Admin\UserController@destroy')->name('destroy')->middleware('permission:users.delete');

resources/views/admin/pages/modals/addContainer.blade.php
@section('modals')
    @parent
    <div class="modal fade" id="add-container-modal" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{__('app.pages.title.addContainer')}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="add-container-form">
                    <div class="modal-body">
                        <input hidden name="section_id" id="section_id">
                        <input hidden name="column_id" id="column_id">
                        <div class="form-group">
                            <label class="label-text">{{__('app.containers.labels.tag')}}</label>
                            <input id="container_tag" name="tag" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label class="label-text">{{__('app.containers.labels.classes')}}</label>
                            <input id="container_classes" name="classes" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="label-text">{{__('app.containers.labels.styles')}}</label>
                            <textarea id="container_styles" name="styles" class="form-control no-jodit"></textarea>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" id="add-container-button" class="btn btn-outline-success"
                                style="margin: 0">{{__('app.create')}}</button>
                        <button type="reset" class="btn btn-outline-light"
                                data-dismiss="modal">{{__('app.close')}}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/modals/addLanguageVersion.blade.php
@section('modals')
    @parent
    <div class="modal fade" id="add-language-version-modal" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{__('app.pages.title.addLanguageVersion')}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{route('admin.pages.addLanguageVersion')}}" method="POST">
                    <div class="modal-body">
                        @csrf
                        <input type="hidden" name="page_id">
                        {{--<input type="hidden" name="origin_lang">--}}
                        <div class="form-group">
                            <label>{{__('app.pages.form.chooseLanguageForPage')}}</label>
                            <div id="languages-select">
                                {{--SELECT INSERTED BY JS--}}
                            </div>
                        </div>
                        <div class="form-group">
                            <label>{{__('app.pages.form.name')}}</label>
                            <input name="name" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label>{{__('app.pages.form.metaTitle')}}</label>
                            <input class="form-control" type="text" name="meta_title" required>
                        </div>
                        <div class="form-group">
                            <label>{{__('app.pages.form.description')}}</label>
                            <textarea class="form-control" name="meta_description"></textarea>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-outline-success">{{__('app.add')}}</button>
                        <button type="reset" class="btn btn-outline-light" data-dismiss="modal">{{__('app.close')}}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/modals/addNewPage.blade.php
@section('modals')
    @parent
    <div class="modal fade" id="add-new-page" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{__('app.pages.title.create')}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{route('admin.pages.store')}}" method="POST">
                    <div class="modal-body">
                        @csrf
                        {{--<input hidden name="language" id="new_language_code">--}}
                        <div class="form-group">
                            <label for="name" class="label-text">{{__('app.pages.form.name')}}</label>
                            <input class="form-control" name="name" id="new_page_name" value="{{old('name')}}" required>
                        </div>
                        <div class="form-group">
                            <label for="meta_title" class="label-text">{{__('app.pages.form.metaTitle')}}</label>
                            <input class="form-control" name="meta_title" id="new_page_meta_title"
                                   value="{{old('meta_title')}}" required>
                        </div>
                        <div class="form-group">
                            <label for="meta_description"
                                   class="label-text">{{__('app.pages.form.description')}}</label>
                            <textarea class="form-control no-jodit" name="meta_description"
                                      id="new_page_meta_description">{!! old('meta_description') !!}</textarea>
                        </div>
                        <div class="animated-checkbox">
                            <label>
                                <input type="checkbox" name="source_from_model" id="source-from-modal-checkbox">
                                <span
                                    class="label-text text-capitalize">{{__('app.pages.form.contentFromModel')}}</span>
                            </label>
                        </div>
                        <div class="form-group">
                            <div id="model-select" style="display: none;">
                                <label>{{__('app.pages.form.modelSelect')}}</label>
                                <select name="source_model_id">
                                    <option disabled
                                            selected>{{__('app.pages.form.modelSelectPlaceholder')}}</option>
                                    @forelse($source_models as $source_model)
                                        <option
                                            value="{{$source_model->id}}">{{__('app.'.\Illuminate\Support\Str::plural($source_model->display_name).'.name')}}</option>
                                    @empty
                                        <option disabled>{{__('app.pages.form.noModelsFound')}}</option>
                                    @endforelse
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-outline-success"
                                style="margin: 0">{{__('app.create')}}</button>
                        <button type="reset" class="btn btn-outline-light"
                                data-dismiss="modal">{{__('app.close')}}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('js')
    @parent
    <script>
        $(document).ready(function () {
            $('body').find('#add-new-page').find('#source-from-modal-checkbox').on('change', function () {
                if ($(this).is(':checked')) {
                    $('body').find('#add-new-page').find('#model-select').attr('style', 'display:block');
                } else {
                    $('body').find('#add-new-page').find('#model-select').attr('style', 'display:none');
                }
            });
        });
    </script>
@endsection

resources/views/admin/pages/modals/addWidget.blade.php
@section('modals')
    @parent
    <div class="modal fade" id="add-widget-modal" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{__('app.pages.title.createWidget')}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="add-section-form">
                    <div class="modal-body">
                        <div class="form-group">
                            <label>{{__('app.pages.form.widgetName')}}</label>
                            <input name="name" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="page_template_id"
                                   class="label-text">{{__('app.pages.form.pageWidgetTemplateChoice')}}</label>
                                <select class="form-control data" name="widget_template_id"
                                        id="widget_template_select"
                                        required>
                                    <option value="" selected
                                            disabled>{{__('app.pages.form.pageWidgetTemplateChoice')}}</option>
                                    @foreach(\Xsoft\Cms\Models\WidgetTemplate::orderBy('name','asc')->get() as $widget_template)
                                        <option value="{{$widget_template->id}}"
                                                @if(old('widget_template_id') == $widget_template->id) selected @endif>{{$widget_template->name}}</option>
                                    @endforeach
                                </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" id="add-widget-button" class="btn btn-outline-success"
                                style="margin: 0">{{__('app.create')}}</button>
                        <button type="reset" class="btn btn-outline-light"
                                data-dismiss="modal">{{__('app.close')}}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/modals/editDetails.blade.php
@section('modals')
    @parent
    <div class="modal fade" id="edit-details" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{__('app.pages.title.editDetails')}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="page_language_id">
                    <div class="form-group">
                        <label>{{__('app.pages.form.name')}}</label>
                        <input class="form-control" type="text" name="name" required>
                    </div>
                    <div class="form-group">
                        <label>{{__('app.pages.form.metaTitle')}}</label>
                        <input class="form-control" type="text" name="meta_title" required>
                    </div>
                    <div class="form-group">
                        <label>{{__('app.pages.form.description')}}</label>
                        <textarea class="form-control no-jodit" name="meta_description"></textarea>
                    </div>
                    <div class="form-group">
                        <label>{{__('app.pages.form.url')}}</label>
                        <div class="row url-input-row">
                            <div class="text-right">
                                <span class="url-span">
                                    {{config('cms.FRONT_DOMAIN').'/'}}
                                </span>
                            </div>
                            <div class="col" style="padding-left: 0">
                                <input class="form-control" type="text" name="url" required>
                            </div>
                        </div>
                        <div class="url-info" style="display: none;">{{__('app.pages.form.urlInfo')}}</div>
                    </div>
                    <div class="animated-checkbox is-main-checkbox">
                        <label>
                            <input type="checkbox" name="is_main" id="page-lang-is-main">
                            <span
                                class="label-text text-capitalize">{{__('app.pages.form.isMain')}}</span>
                        </label>
                    </div>
                    {{--<h4 class="mt30">{{__('app.pages.options')}}</h4>--}}
                    {{--<div class="options">--}}

                    {{--</div>--}}
                </div>
                <div class="modal-footer">
                    @if(auth()->user()->hasPermission('pages.delete'))
                        <button type="button" id="deletePage"
                                class="btn btn-outline-danger margin-right-auto"
                                style="display:none;">{{__('app.deleteButton.title')}}</button>
                    @endif
                    <button type="button" id="submit-details" class="btn btn-outline-success">{{__('app.update')}}</button>
                    <button type="reset" class="btn btn-outline-light" data-dismiss="modal">{{__('app.close')}}</button>
                </div>
                @if(auth()->user()->hasPermission('pages.delete'))
                    <div class="delete-content">
                        <h3>{{__('app.pages.questions.delete')}}<br>
                            <small>({{__('app.pages.deleteWarning')}})</small>
                        </h3>
                        <div class="row">
                            <form action="{{route('admin.pages.delete')}}" method="POST">
                                <input type="hidden" name="page_language_id">
                                @csrf
                                <div class="col-12">
                                    <button type="submit" id="deletePageConfirm"
                                            class="btn btn-outline-danger">{{__('app.deleteButton.confirm')}}</button>
                                    <button type="reset" id="deletePageCancel"
                                            class="btn btn-outline-light">{{__('app.deleteButton.cancel')}}</button>
                                </div>
                            </form>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/modals/importExport.blade.php
@section('modals')
    @parent
    <div class="modal fade" id="export-page" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{__('app.pages.title.export')}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{__('app.pages.questions.export')}}
                </div>
                <div class="modal-footer">
                    <button type="button" id="confirm-export-page"
                            class="btn btn-outline-success">{{__('app.confirm')}}</button>
                    <button type="reset" class="btn btn-outline-light" data-dismiss="modal">{{__('app.close')}}</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="export-all-pages" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{__('app.pages.title.export')}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{__('app.pages.questions.export')}}
                </div>
                <div class="modal-footer">
                    <a href="{{route('admin.pages.exportAll')}}"
                       class="btn btn-success">{{__('app.confirm')}}</a>
                    <button type="reset" class="btn btn-primary" data-dismiss="modal">{{__('app.close')}}</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="import-new-page" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="{{route('admin.pages.import')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('POST')
                    <div class="modal-header">
                        <h5 class="modal-title">{{__('app.pages.title.import')}}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <input type="file" name="import_file">
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-outline-success">{{__('app.pages.import')}}</button>
                        <button type="reset" class="btn btn-outline-light" data-dismiss="modal">{{__('app.close')}}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/modals/moveWidget.blade.php
@section('modals')
    @parent
    <div class="modal fade" id="move-widget-modal" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{__('app.pages.title.moveWidget')}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <h3>{{__('app.pages.form.moveWidgetQuestion')}}</h3>
                    </div>
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" id="move-widget-button" class="btn btn-outline-success">{{__('app.move')}}</button>
                    <button type="button" id="copy-widget-button" class="btn btn-outline-info">{{__('app.copy')}}</button>
                    <button type="reset" class="btn btn-outline-light"
                            data-dismiss="modal">{{__('app.cancel')}}</button>
                </div>
            </div>
        </div>
    </div>
@endsection